### ISSUE TITLE
Update to Django 2.0 

### ISSUE THREAD

**Issue by Dikshant007** [miguelrochajr/DjangoFullStackBootcamp_Course#1]
Can you please update this blog clone project to Django 2.0 because I am not able to edit, remove, publish and comment 
I am not able to convert the code according to latest version of Django so please help

**Comment by miguelrochajr** [comment]
Unfortunately I won't update this project for django 2.0. This was the code I produced while learning Django 1.11. Thus, this code is for a specific version of django. If you want to have an updated code, please search fo Jose Portilla's course on Udemy, since this was the course I took while creating this repository.
